
services:
  db:
    build: .
    container_name: Phoenicia-Digital-Database
    environment:
      POSTGRES_USER: phoeniciadigital
      POSTGRES_PASSWORD: pdsoftware
      POSTGRES_DB: pd_database
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
